stages:
  - build

before_script:
  - pip install --upgrade pip

build-package-job:
  stage: build
  image: python:3.10
  script:
    - pip install twine
    - python3 -m pip install --upgrade build
    - python3 -m build
    - twine check dist/*
    - twine upload dist/*
  only:
    - tags
