stages:
  - build

before_script:
  - pip install --upgrade pip

build-package-job:
  stage: build
  image: python:3.10
  script:
    - pip install twine
    - python3 setup.py sdist
    - python3 twine check dist/*
    - python3 twine upload dist/*
  only:
    - tags
