name: mobius
channels:
  - conda-forge
  - pyg
  - defaults
dependencies:
  - python 3.10|3.11
  - botorch
  - fair-esm
  - grakel
  - gpytorch
  - matplotlib
  - numba 
  - numpy == 1.26.4
  - numpydoc
  - pandas
  - parmed
  - prody
  - pdbfixer
  - pip
  - pytorch_geometric
  - pytorch-scatter
  - openmm
  - rdkit
  - seaborn
  - sentencepiece
  - scikit-learn
  - scipy
  - sphinx == 6.2.1
  - sphinx_rtd_theme
  - tqdm
  - transformers
  - pytorch=*=*cuda*
  - pip:
    - mhfp
    - ray
    - pymoo
    - mapchiral
    - numpy == 1.26.4
    - git+https://github.com/forlilab/scrubber.git
