name: mobius
channels:
  - conda-forge
  - defaults
dependencies:
  - python <=3.10
  - botorch
  - fair-esm
  - gpytorch
  - matplotlib
  - numba 
  - numpy
  - numpydoc
  - pandas
  - parmed
  - pdbfixer
  - pip
  - openmm
  - rdkit
  - seaborn
  - sentencepiece
  - scikit-learn
  - scipy
  - sphinx == 6.2.1
  - sphinx_rtd_theme
  - transformers
  - pytorch=*=*cuda*
  - pip:
    - mhfp
    - ray
    - pymoo
    - prody
