name: mobius
channels:
  - conda-forge
  - defaults
dependencies:
  - python <=3.10
  - botorch
  - gpytorch
  - matplotlib
  - numpy
  - numpydoc
  - pandas
  - pip
  - rdkit
  - seaborn
  - scikit-learn
  - scipy
  - sphinx == 6.2.1
  - sphinx_rtd_theme
  - pytorch
  - pip:
    - mhfp
    - ray
