name: Mirror GitLab Repository

on:
  schedule:
    - cron: '*/30 * * * *'  # Triggers the workflow every 30 minutes
  workflow_dispatch:

jobs:
  mirror-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository from GitLab
        run: |
          git clone -b master https://git.scicore.unibas.ch/schwede/mobius.git /tmp/repo

      - name: GitHub config
        run: |
          cd /tmp/repo
          git config --local user.email env.EMAIL
          git config --local user.name env.USERNAME
          git remote set-url origin git@github.com:jeeberhardt/mobius.git
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
