name: Mirror GitLab Repository

on:
  schedule:
    - cron: '*/30 * * * *'  # Triggers the workflow every 30 minutes
  workflow_dispatch:

jobs:
  mirror-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository from GitLab
        run: |
          git clone https://git.scicore.unibas.ch/schwede/mobius.git /tmp/repo

      - name: Push to GitHub
        run: |
          cd /tmp/repo
          git push https://github.com/jeeberhardt/mobius.git master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
